### ISSUE TITLE
Library seems not to work for services with input parameters

### ISSUE THREAD

**Issue by SchwertAs** [bfueldner/tr064#1]
Hello Mr. Füldner,

I tried your library with great success in retrieving Information from a Fritz box and also forked it for debugging purposes. It works fine for all service Actions, which do not contain input parameters. Every other requests end in a code 500 (Internal Server error) from the Fritz AJAX server. Here is a example request, which does not work:

`<?xml version='1.0' encoding='utf-8'?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
	<s:Body>
		<u:GetAppMessageFilter xmlns:u="urn:dslforum-org:service:X_AVM-DE_AppSetup:1">
			<NewAppId>PowMonitor</NewAppId>
		</u:GetAppMessageFilter>
	</s:Body>
</s:Envelope>`

Maybe the request is malformed. I am authorised as a natural boxuser with all rights except remote access by internet. Here the calling Python code:

`import tr064

client = tr064.Client('<Username>', '<password>', 'http://192.168.178.1:49000')
getFil = client.InternetGatewayDevice.X_AVM_DE_AppSetup.GetAppMessageFilter
getFil(**{**{'NewAppId': 'PowMonitor' } } )`

Can you give me a hint about correct usage?

**Comment by SchwertAs** [comment]
This seems to be only an issue in the AppSetup service. Maybe it depends on an internal State of the fritz box.

**Comment by bfueldner** [comment]
Regarding the usage of the `tr064` library your code is correct. I've used the library to change e.g. WLAN SSID or turn WLAN on or off. The following usage example changes the SSID of the first (internal) WLAN adapter:

    client = tr064.Client('user', 'xxxxx', 'https://fritz.box:49443')
    client.LANDevice.WLANConfiguration[1].SetSSID(NewSSID='TestWLAN')
    res = client.LANDevice.WLANConfiguration[1].GetSSID()

    #  {'NewSSID': 'TestWLAN'}

Note: I used encrypted transport over port 49443, but the example works also with unencrypted port 4900.

I've never used the AppSetup service. Did you take a look at the `x_appsetup.pdf` on https://avm.de/service/schnittstellen/? In chapter *3.1 GetAppMessageFilter* there is a hint on the security context of this action. Perhaps this may point to the right direction?

**Comment by bfueldner** [comment]
So here is how it works:

First register new application with natural user credentials:

```
client.InternetGatewayDevice.X_AVM_DE_AppSetup.RegisterApp(
    NewAppId='TestApp',
    NewAppDisplayName='My test application',
    NewAppDeviceMAC='',
    NewAppUsername='testuser',
    NewAppPassword='testpassword',
    NewAppRight='RW',
    NewNasRight='NO',
    NewPhoneRight='RW',
    NewHomeautoRight='NO',
    NewAppInternetRights='0'
)
```

Login with your new created app user credentials:

```
client = tr064.Client('testuser', 'testpassword', 'https://fritz.box:49443')
res = client.InternetGatewayDevice.X_AVM_DE_AppSetup.GetAppMessageFilter(NewAppId='TestApp')

# {'NewFilterList': '<List />\n'}
```
